development:
  clients:
    default:
      database: my_app_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: my_app_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: my_app_production
      hosts:
        - db.example.com:27017
